// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CoreContext.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace CoreContext.Data.Configurations
{
    public partial class RoleConfiguration : IEntityTypeConfiguration<Role>
    {
        public void Configure(EntityTypeBuilder<Role> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreateOn).HasColumnType("datetime");
            entity.Property(e => e.DeleteOn).HasColumnType("datetime");
            entity.Property(e => e.UpdateOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreateByNavigation).WithMany(p => p.RoleCreateByNavigations).HasForeignKey(d => d.CreateBy);

            entity.HasOne(d => d.CreateSourceNavigation).WithMany(p => p.Roles)
            .HasForeignKey(d => d.CreateSource)
            .HasConstraintName("FK_Roles_Reasons_CreateSource");

            entity.HasOne(d => d.DeleteByNavigation).WithMany(p => p.RoleDeleteByNavigations).HasForeignKey(d => d.DeleteBy);

            entity.HasOne(d => d.DeleteReasonNavigation).WithMany(p => p.RoleDeleteReasonNavigations)
            .HasForeignKey(d => d.DeleteReason)
            .HasConstraintName("FK_Roles_Reasons_Delete");

            entity.HasOne(d => d.UpdateByNavigation).WithMany(p => p.RoleUpdateByNavigations).HasForeignKey(d => d.UpdateBy);

            entity.HasOne(d => d.UpdateReasonNavigation).WithMany(p => p.RoleUpdateReasonNavigations)
            .HasForeignKey(d => d.UpdateReason)
            .HasConstraintName("FK_Roles_Reasons_Update");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Role> entity);
    }
}
