// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using CoreContext.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

#nullable disable

namespace CoreContext.Data.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.Property(e => e.Id).ValueGeneratedNever();
            entity.Property(e => e.CreateOn).HasColumnType("datetime");
            entity.Property(e => e.DeleteOn).HasColumnType("datetime");
            entity.Property(e => e.UpdateOn).HasColumnType("datetime");

            entity.HasOne(d => d.CreateByNavigation).WithMany(p => p.InverseCreateByNavigation).HasForeignKey(d => d.CreateBy);

            entity.HasOne(d => d.CreateSourceNavigation).WithMany(p => p.Users)
            .HasForeignKey(d => d.CreateSource)
            .HasConstraintName("FK_Users_Reasons_CreateSource");

            entity.HasOne(d => d.DeleteByNavigation).WithMany(p => p.InverseDeleteByNavigation).HasForeignKey(d => d.DeleteBy);

            entity.HasOne(d => d.DeleteReasonNavigation).WithMany(p => p.UserDeleteReasonNavigations)
            .HasForeignKey(d => d.DeleteReason)
            .HasConstraintName("FK_Users_Reasons_Delete");

            entity.HasOne(d => d.UpdateByNavigation).WithMany(p => p.InverseUpdateByNavigation).HasForeignKey(d => d.UpdateBy);

            entity.HasOne(d => d.UpdateReasonNavigation).WithMany(p => p.UserUpdateReasonNavigations)
            .HasForeignKey(d => d.UpdateReason)
            .HasConstraintName("FK_Users_Reasons_Update");

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
