// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;

namespace CoreContext.Models;

public partial class Reason
{
    public Guid Id { get; set; }

    public string Name { get; set; } = null!;

    public string? Description { get; set; }

    public DateTime CreateOn { get; set; }

    public Guid? CreateBy { get; set; }

    public Guid? CreateSource { get; set; }

    public DateTime? UpdateOn { get; set; }

    public Guid? UpdateBy { get; set; }

    public Guid? UpdateReason { get; set; }

    public DateTime? DeleteOn { get; set; }

    public Guid? DeleteBy { get; set; }

    public Guid? DeleteReason { get; set; }

    public bool IsDeleted { get; set; }

    public virtual ICollection<Company> CompanyDeleteReasonNavigations { get; set; } = new List<Company>();

    public virtual ICollection<Company> CompanyUpdateReasonNavigations { get; set; } = new List<Company>();

    public virtual User? CreateByNavigation { get; set; }

    public virtual Source? CreateSourceNavigation { get; set; }

    public virtual User? DeleteByNavigation { get; set; }

    public virtual Reason? DeleteReasonNavigation { get; set; }

    public virtual ICollection<Reason> InverseDeleteReasonNavigation { get; set; } = new List<Reason>();

    public virtual ICollection<Reason> InverseUpdateReasonNavigation { get; set; } = new List<Reason>();

    public virtual ICollection<Role> RoleDeleteReasonNavigations { get; set; } = new List<Role>();

    public virtual ICollection<Role> RoleUpdateReasonNavigations { get; set; } = new List<Role>();

    public virtual ICollection<Source> SourceDeleteReasonNavigations { get; set; } = new List<Source>();

    public virtual ICollection<Source> SourceUpdateReasonNavigations { get; set; } = new List<Source>();

    public virtual User? UpdateByNavigation { get; set; }

    public virtual Reason? UpdateReasonNavigation { get; set; }

    public virtual ICollection<User> UserDeleteReasonNavigations { get; set; } = new List<User>();

    public virtual ICollection<User> UserUpdateReasonNavigations { get; set; } = new List<User>();
}